const configuration = {
    personal: {
        firstName: "Sina",
        lastName: "Farhadi",
        description: "Senior Frontend Developer | Expert in React.js, Next.js, and Svelte | Specializing in Full-Stack Web Applications and Blockchain Technologies",
        skills: {
            Frontend: [
                "React.js",
                "Next.js",
                "Svelte",
                "Astro",
                "Redux",
                "MobX",
                "TypeScript",
                "JavaScript",
                "Deck.gl",
                "Mapbox",
                "D3.js",
                "Three.js",
                "WebGL",
                "WebRTC",
                "WebSockets",
                "PWA",
                "Chrome Extensions",
                "React Native",
                "Flutter",
                "SASS",
                "Material UI",
                "Tailwind CSS",
                "Styled Components",
                "Jest",
                "Cypress",
                "Storybook",
                "Figma",
                "Playwright",
                "OpenLayers",
            ],
            Backend: [
                "Node.js",
                "Express.js",
                "Nest.js",
                "Python",
                "Django",
                "Flask",
                "MongoDB",
                "GraphQL",
                "Apollo",
                "REST",
                "Firebase",
                "AWS",
                "Netlify",
                "Vercel",
                "Docker",
                "Nginx",
                "Linux"
            ],
            Blockchain: [
                "Solidity",
                "Web3.js",
                "Truffle",
                "Smart Contracts",
                "Metamask",
                "Wallet Connect",
                "Ethers.js",
            ],
            Tools: [
                "Git",
                "GitHub",
                "Jira",
                "Agile",
                "Scrum",
                "Kanban",
                "Trello",
                "Slack",
                "Discord"
            ],
            Techniques: [
                "Responsive Design",
                "Cross-Browser Compatibility",
                "Functional Programming",
                "Micro-Frontends",
                "Micro-Services",
                "Serverless",
                "Progressive Web Apps",
                "Flux",
                "MVC",
                "MVVM",
                "REST",
                "SSR",
                "SSG",
                "SPA",
                "MPA"
            ],
            SoftSkills: [
                "Teamwork",
                "Communication",
                "Leadership",
                "Problem Solving",
                "Critical Thinking",
                "Time Management",
                "Organization",
                "Adaptability",
                "Creativity"
            ],
        },
    },
    assets: {
        image: "/profile.jpeg",
        loadingGif: "/bean.gif",
    },
    socials: {
        linkedin: "https://linkedin.com/in/sina-farhadi",
        github: "https://github.com/cinaaaa",
        medium: "https://medium.com/@sinafarhadi",
        scroll: "#posts",
    },
    colors: {
        primary: "#0E1116",
        secondary: "#EFF6EE",
    },
    contact: {
        email: "hey@bugpointer.com"
    },
};

export default configuration;
